from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LAUNCHER = ROOT / "windows" / "launcher.py"


def main() -> None:
    """Harden the existing launcher without replacing its startup/background logic.

    The launcher is now generated by the persistence/background patch. Older
    versions of this script replaced the whole main() function and could remove
    run_server(), causing the packaged EXE to crash with NameError. Keep this
    patch intentionally small and idempotent.
    """
    text = LAUNCHER.read_text(encoding="utf-8")

    # Disable GPU acceleration before importing pywebview. This is only a
    # WebView2 compatibility setting; it does not replace the launcher logic.
    if "WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS" not in text:
        marker = "import webview\n"
        if marker in text:
            text = text.replace(
                marker,
                'import os\nos.environ.setdefault("WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS", "--disable-gpu")\n\nimport webview\n',
                1,
            )

    # Safety checks: the packaged launcher must retain the actual server and
    # entry point. Do not rewrite them here.
    required = ("def run_server(", "def main(", "if __name__ == \"__main__\":")
    missing = [item for item in required if item not in text]
    if missing:
        raise SystemExit("Launcher validation failed; missing: " + ", ".join(missing))

    LAUNCHER.write_text(text, encoding="utf-8")
    print("Windows runtime compatibility patch applied without replacing launcher main().")


if __name__ == "__main__":
    main()
